### ISSUE TITLE
Tab bar hidding content

### ISSUE THREAD

**Issue by flowbe** [eRGoon/RGPageViewController#2]
Hello,
I used your awesome project in my app but the tab bar hide a part of my table view. How to fix that ?

Thanks

**Comment by sakae-nakajima** [comment]
I was having a similar issue. My one had an issue with the first view controller, and the rest were fine. The following code in setupSelf function solved the issue for me. 

// old line
self.selectTabAtIndex(0)

// new lines
var time = dispatch_time(DISPATCH_TIME_NOW, Int64(0.1 \* Double(NSEC_PER_SEC)))
dispatch_after(time, dispatch_get_main_queue(), {
    self.selectTabAtIndex(0)
})

There must be a proper way to solve this, but for now, this did the job.

**Comment by eRGoon** [comment]
I'm working on a fix for this, but I need some additional testing.

for now, i would suggest the fix from sakae-nakajima, but unfortunately this will not work if your contentViewControllers are TableViewControllers or CollectionViewControllers.
I don't have a fix for this yet, so I recommend using a normal UIViewController that holds a TableView instead

**Comment by eRGoon** [comment]
I submitted a new version today that should fix this issue.

But it's a big Update with a lot of changes. Please refer to the Readme

**Comment by sakae-nakajima** [comment]
Thanks, the issue still remains. I noticed some code block has been commented out in viewControllerAtIndex, is this intentional? It works fine when I bring the code block though.

**Comment by eRGoon** [comment]
oh shoot.

that was indeed by accident

thanks

**Comment by flowbe** [comment]
Hello, I downloaded the new version and it doesn't seems to work. Are they other changes to do ?
I will try to work on it later, maybe my code isn't good.

PS: my content is a UITableViewController

**EDIT:** I replaced my UITableViewController by a UIViewController with a UITableView in it and it works !

**Comment by loganisitt** [comment]
The constraints are off, I changed them for layout I'm using. Easy fix.
